@startuml
'https://plantuml.com/class-diagram

' 아카데미 운영팀, 독도박물관, 해설사 부모 클래스
/'
    _id : uuid (PK)

'/
class User {
    + (PK)uuid _id
    + String username
    - String password
    + String name
    + String email
    + String phone
    + String avatar
    + Role
}

' 사용자 구분 Enum
enum Role {
    ADMIN
    USER
    GUIDE
    MUSEUM
}

' 아카데미 운영팀
class Admin {
}

ADMIN --|> User

' 독도박물관
class Museum {
}

MUSEUM --|> User

' 해설사

class Guide {
}

GUIDE --|> User

' 사용자
class Member {
    + String _id
    + String name
    + String phone
    + String sex
    + String birthday
    + String locale
    + String subLocale
    + String department
    + String job
    + String jobPhone
    + String tagName
    + Boolean discount
    + Boolean isPaid
    + Member roomMate
}

' 사용자 결제 정보
class MemberPayment {
    + String _id
    + String managerName  ' 결제 담당자 이름
    + String managerPhone ' 결제 담당자 연락처
    + String account      ' 계좌번호
    + String bank         ' 은행
    + String depositor    ' 예금주
    + String paymentDate  ' 결제일
    + String paymentType  ' 결제 방법
    + String paymentAmount ' 결제 금액
    + String paymentStatus ' 결제 상태
}


@enduml