@startuml

!define primary_key(x) <b><color:#b8861b><&key></color> x</b>
!define foreign_key(x) <color:#aaaaaa><&key></color> x
!define column(x) <color:#efefef><&media-record></color> x
!define table(x) entity x << (T, white) >>

' ----------------------------------------
' 유저 관련 테이블
' ----------------------------------------

' User Role
enum UserRole {
    Admin
    User
    Museum
}

' 유저 테이블
table("users") {
    primary_key("_id"): UUID
    column("username"): String
    column("password"): String
    column("name"): String
    column("email"): String
    column("phone"): String
    column("avatar"): String
    column("Role"): UserRole
}

' 참가자 테이블
table("members") {
    primary_key("_id"): UUID
    column("name"): String
    column("phone"): String
    column("sex"): String
    column("birth"): String
}

' company 테이블
table("companies") {
    primary_key("_id"): UUID
    column("name"): String
    column("locale"): String
    column("sub_locale"): String
    column("department"): String
    column("position"): String
    column("phone"): String
}

' 참가자 결제 정보 테이블
table("payments") {
    primary_key("_id"): UUID
    column("manager"): String
    column("manager_phone"): String
    column("account"): String
    column("bank"): String
    column("payment_date"): String
    column("payment_amount"): String
    column("payment_status"): String
    column("payment_method"): String
    ' 도민할인
    column("discount"): Boolean
}

' ----------------------------------------
' 협력 업체 관련 테이블
' ----------------------------------------

' 버스 회사 테이블
table("bus_companies") {
    primary_key("_id"): UUID
    column("name"): String
    column("phone"): String
    column("address"): String
    column("contact"): String
    column("contact_phone"): String
}

' 식당 테이블
table("restaurants") {
    primary_key("_id"): UUID
    column("name"): String
    column("phone"): String
    column("address"): String
    column("contact"): String
    column("contact_phone"): String
}

' 식당 메뉴 테이블
table("restaurant_menus") {
    primary_key("_id"): UUID
    column("name"): String
    column("price"): String
    column("description"): String
    column("image"): String
}

' 선사 테이블
table("cruise_companies") {
    primary_key("_id"): UUID
    column("name"): String
    column("phone"): String
    ' 선사 주소
    column("address"): String
    ' 선사 집결지
    column("meeting_place"): String
    column("contact"): String
    column("contact_phone"): String
}

' 선박 테이블
table("cruise_ships") {
    primary_key("_id"): UUID
    foreign_key("cruise_company_id"): UUID
    column("name"): String
}

' 선박 스케쥴 테이블
table("cruise_schedules") {
    primary_key("_id"): UUID
    foreign_key("cruise_ship_id"): UUID
    column("start_time"): String
    column("end_time"): String
    column("start_place"): String
    column("end_place"): String
}



' ----------------------------------------
' 투어 관련 테이블
' ----------------------------------------

' tour session 테이블
table("tour_sessions"){
    primary_key("_id"): UUID
    ' 투어 이름 - 2019년도 투어
    column("name"): String
    column("tour_year"): String
    ' 주최 기관
    column("sponsor"): String
}


' tour 테이블 - 해당 년도 투어 정보
table("tours"){
    primary_key("_id"): UUID
    column("number"): String
    column("start_date"): Date
    column("end_date"): Date
    ' 집결지, 집결 시간
    column("meeting_place"): String
    column("meeting_time"): String
}

' ----------------------------------------
' 그룹 관련 테이블
' ----------------------------------------

' 그룹 테이블 - 투어의 호차별 그룹
table("groups"){
    primary_key("_id"): UUID
    foreign_key("bus_company_id"): UUID
    column("number"): Number
    column("bus_number"): String
    column("bus_image"): String
    column("bus_company"): String
}




' ------------RELATIONSHIP----------------
users -- UserRole : has

' ----------- MEMBER----------------------
' 참가자 기본 정보
' 참가자 - 회사 (1:N)
members --o{ companies : one to many
' 참가자 - 결제 정보 (1:N)
members -- payments : one to one
' 참가자 - 투어 (N:1)
members }-- tour : many to one


' ----------- TOUR -----------------------
' 투어 - 투어 세션 (1:N)
tour_sessions --o{ tours : one to many


' 그룹 - 버스 회사 (1:N)
groups --o{ bus_companies : one to many



cruise_companies --o{ cruise_ships : one to many
cruise_ships --o{ cruise_schedules : one to many



@enduml